# Generated by Django 6.0.7 on 2026-07-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=1)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
            ],
            options={
                'db_table': 'skills',
                'unique_together': {('user_id', 'skill_name')},
            },
        ),
    ]
